### ISSUE TITLE
Website using a lot of CPU

### ISSUE THREAD

**Issue by Jamadoh** [nORbDragon/e7vault-issues#21]
I don't actually know if my computer have a problem or if the website have a problem but i used the website before without any problem and since maybe a month or more the animation are laging and the website use a lot of my CPU

**Comment by nORbDragon** [comment]
> the animation are laging and the website use a lot of my CPU

For all portraits or only for some new ones? Like "ae-" collab. Their new (?) artist is starting to annoy me with an inadequate amount of special effects in the background. Because of them, the frame rate drops and there may be lags when interacting with the interface while viewing the portrait. The first such portrait with an overabundance of special effects is the portrait of Arbiter Vildred (rta skin).

Or maybe you just disabled **"hardware acceleration"** in browser for some reason? More info about **"hardware acceleration"** - https://support.wevideo.com/hc/en-us/articles/225259448-How-can-I-enable-WebGL-

If your problem is not related to this switch, then write with which portraits you have a problem. And your Device/OS/Browser.

**Comment by nORbDragon** [comment]
BTW: found good fix for my old notebook with **dual Intel + Nvidia** graphics cards - https://alteredqualia.com/texts/optimus/

This is fixed my troubles.

**Comment by Jamadoh** [comment]
Oh f*ck sorry, indeed the hardware acceleration was disabled, but thanks for your reactivity !

**Comment by nORbDragon** [comment]
Good. =) I close this issue, then.
