### ISSUE TITLE
Request: Is it possible to add character models in viewer in addition to portraits?

### ISSUE THREAD

**Issue by aaronxu106** [nORbDragon/e7vault-issues#9]
First of all, much appreciated for setting up the site for viewing portraits live2d animation! 
Just wondering if it is possible to set up the viewer for character models as well, which is the in battle live2d.
Or include the .json and .atlas file in patch history maybe?

Thank you very much!
Aaron

**Comment by nORbDragon** [comment]
Yo.

> Just wondering if it is possible to set up the viewer for character models as well, which is the in battle live2d.

Model viewer (alpha stage) you can find on my "playground" - https://www.norbdragon.com/e7vault/model-viewer.html?id=yulha

There are a lot of bugs and glitches with character models, so this is not yet on the main site (e7vault). Well, because of the *"geopolitical situation in the world"* I'm not in the mood to work on solving these problems yet.

I am looking to finding another hosting vps-/cloud-platform to host my resources if the ability to pay for services abroad (from Russia) is not unlocked by September. The sanctions even got to me. So, I have very crappy mood. =)

> Or include the .json and .atlas file in patch history maybe?

Err... If json-files were just lying around in the client, e7herder would not have closed.

The game uses its own data format (scsp, not json/skel). I'm converting it with my own scripts into json-format I need. That is, the files used on my resource are an unofficial file conversion from the game client. They may contain errors due to my misunderstanding of scsp-format.

If someone really needs the files (json/atlas/png), they usually *"steal"* them on their own, without asking my permission. =) And I am not against this approach. This is the internet. If something is posted in the public domain, then it can be taken away.

You can find json/atlas/png files for character by use custom link like:
- https://www.e7vau.lt/static/game/portrait/c1131.atlas
- https://www.e7vau.lt/static/game/portrait/c1131.json
- https://www.e7vau.lt/static/game/portrait/c1131.png

, where **c1131** - character ID from game. You can find the character ID on e7vault.

For character portraits, I have already implemented storing the history of their changes. I did not plan to store the history of changes for combat sprites. But if Aria's combat sprites are also censored, I think I'll work on the history for this mode as well.

You can find all the changes for the character of interest simply by entering the name of the character or his ID in the search field:
- https://www.e7vau.lt/portrait-viewer.html?stab=0&sname=doris
- https://www.e7vau.lt/portrait-viewer.html?stab=1&sid=c4044

**Comment by aaronxu106** [comment]
Much appreciated!

**Comment by aaronxu106** [comment]
It is difficult times.. not just about politics, it is also about economy, it was the only fun for me to collect game models (and to practice some programming skills) due to the pandemic. Hope everything will be better soon, even though soon might be a decade..Anyway, thank you very much for your work! You are a true hero.
